### ISSUE TITLE
Status of of xiao-berylline branch?

### ISSUE THREAD

**Issue by pupto-bismol** [jcmkk3/trochilidae#12]
Also just a question, not an issue:

I noticed the branch name here https://github.com/jcmkk3/trochilidae/tree/xiao-berylline and I am assuming that you plan to have a xiao BLE version of berylline at some point in the future - based off of the fact that I imported the berylline/berylline.kicad_pcb file into my own kicad and did not see the xiao footprint yet. 

Do you have any estimate on when/how this will be done, or info on if you will add printable files to the releases page when finished? I'm quite interested in printing this board myself and would like to do so with xiao controllers instead of nice!nanos if possible.

I'm also quite interested in the design differences between the berylline v1 and the min-spaced version. Looking at the product page for the CS keycaps used in the original photos, they are said to be made for 17x18mm spacing, so the minimum spaced version would not fit those (and I was really hoping to get to try out those keycaps). Also curious on the reasoning for not keeping the tenting puck holes and adding a new splay angle between the index and middle columns - do you find the splay layout is more comfortable?

**Comment by jcmkk3** [comment]
Hi @pupto-bismol,

I've toyed with the idea of a xiao based berylline before, but I don't know if I'll ever do it. The reason is that the xiao doesn't have a convenient built-in place for a battery like a nice!nano does. It also would make the build more complicated because it would require diodes.

I think that I originally made that repo with the intention of experimenting, but the real experiments were in a case design. I never changed anything with the pcb to support a xiao, but knew that if I was going to do that, I'd need a case to hold a battery. I kept it around as an example for myself on a simple case design.

The choc min-spaced version is meant for pseudoku's Philadelphia Minimalist (PM) keycaps instead of Chicago Steno (CS). There aren't any cast versions that you can buy from asymplex, unfortunately. You can only print them. The source files can be found in this repo: https://github.com/pseudoku/PseudoMakeMeKeyCapProfiles

Pseudoku did an export for me of 14.5 x 14.5 sized keycaps that are the perfect size for chocs. You can find those in the low profile keyboard discord https://discord.gg/xmQtdVRBKg
A direct link to the post: https://discord.com/channels/669011382284451861/831948386198093834/970866610095157309

The reason that the tenting puck holes went away is because there wasn't a good place to put the mounting holes for the puck that didn't interfere with the switches in the condensed spacing. The splay angles were tweaked to compensate for the overall key spacing being more narrow.

I'm going to close this issue, but feel free to ask more questions here if you'd like. You can also ask questions in my channel on the absolem keyboard server https://discord.gg/PaCpa2uX8B

**Comment by pupto-bismol** [comment]
Thanks for the feedback! Right now I'm working in a local repo adding some of the modifications I want, including adapting berylline for a xiao BLE, adding two extra pinky keys, putting the spacing at standard choc 17x18, and possibly adding an encoder. When I'm done with everything would you want me to open a PR? I could open one with or without the extra pinky keys - stuff like the precise spacing of the splayed columns may not be the same still, though I kept the angles the same, and the edge cuts will probably not be the same as they were. But I would be happy to contribute if you'd like

**Comment by jcmkk3** [comment]
It’s great to hear that you’re making it your own. No need to contribute back. One of my goals with these designs was to give a starting point that others could remix and extend to their own needs. It would be great if you published it to your own repo so that others could use/remix your design as well. I’d be happy to see the final result.
